name: cml_tfr
channels:
  - sebp
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=16.1.0
  - astor=0.8.1
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - autograd=1.5
  - autograd-gamma=0.5.0
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.27
  - aws-c-io=0.13.11
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - bokeh=2.4.3
  - boltons=23.0.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.4.26
  - certifi=2024.8.30
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=3.0.0
  - coloredlogs=15.0.1
  - comm=0.2.1
  - conda=23.9.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.9.3
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=0.12.2
  - dask=2023.5.0
  - dask-core=2023.5.0
  - dask-glm=0.2.0
  - dask-ml=2024.4.4
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.5.0
  - ecos=2.0.12
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - fftw=3.3.9
  - fmt=9.1.0
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - formulaic=0.6.2
  - freetype=2.13.3
  - fsspec=2024.6.1
  - future=0.18.3
  - gflags=2.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - graphlib-backport=1.0.3
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h5py=3.11.0
  - hdf5=1.12.1
  - heapdict=1.0.1
  - httpcore=1.0.2
  - httpx=0.27.0
  - humanfriendly=10.0
  - icu=73.1
  - idna=3.4
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2021.4.0
  - interface_meta=1.3.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.6
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.6.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.2.1
  - libdeflate=1.22
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=15.1.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libllvm14=14.0.6
  - libmamba=1.5.1
  - libmambapy=1.5.1
  - libnghttp2=1.52.0
  - libosqp=0.6.3
  - libpng=1.6.39
  - libpq=12.20
  - libprotobuf=4.25.3
  - libqdldl=0.1.7
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lifelines=0.27.8
  - llvmlite=0.41.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - multipledispatch=0.6.0
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - notebook-shim=0.2.3
  - numba=0.58.1
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - onnxruntime=1.18.1
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.5.0
  - orc=2.0.1
  - osqp=0.6.3
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.1
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - plotly=5.24.1
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.7.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - protobuf=4.25.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.15.1
  - pynndescent=0.5.10
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python-lmdb=1.4.1
  - python-tzdata=2025.2
  - python_abi=3.8
  - pytz=2024.1
  - pywavelets=1.4.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qdldl-python=0.1.7.post0
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - s2n=1.3.30
  - scikit-image=0.20.0
  - scikit-learn=1.3.0
  - scikit-survival=0.22.2
  - scipy=1.9.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - sympy=1.13.3
  - tbb=2021.8.0
  - tblib=1.7.0
  - tenacity=9.0.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tifffile=2020.10.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.4.1
  - tqdm=4.65.0
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2025b
  - umap-learn=0.5.6
  - unicodedata2=15.1.0
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.41.2
  - wrapt=1.14.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.4.2
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
