
IMAGE_VARIABLES_TFR = [
 'Hemavision ID',
 'Sample_Area',
 'Empty_Sample_Area',
 'RBC_Sample_Area',
 'Eukaryote_Sample_Area',
 'Stroma_Sample_Area',
 'Empty_Sample_Proportion',
 'RBC_Sample_Proportion',
 'Eukaryote_Sample_Proportion',
 'Stroma_Sample_Proportion',
 'Megakaryocyte_Sample_Count',
 'Megakaryocyte_Stroma_Count',
 'Megakaryocyte_Stroma_Count_Proportion',
 'Megakaryocyte_Sample_Density',
 'Megakaryocyte_Stroma_Density',
 'Megakaryocyte_Sample_Area',
 'Megakaryocyte_Stroma_Area',
 'Megakaryocyte_Sample_Area_Mean',
 'Megakaryocyte_Stroma_Area_Mean',
 'Lipid_Small_Sample_Area',
 'Lipid_Medium_Sample_Area',
 'Lipid_Large_Sample_Area',
 'Lipid_Total_Sample_Area',
 'Lipid_Small_Sample_Proportion',
 'Lipid_Medium_Sample_Proportion',
 'Lipid_Large_Sample_Proportion',
 'Lipid_Total_Sample_Proportion',

 'All_Cells',
 'Living_Cells',
 'Artefacts',
 'Atypical lymphocytes',
 'Basophils',
 'Blasts',
 'Eosinophils',
 'Erythroblasts',
 'Neutrophils',
 'Lymphocytes',
 'Megakaryocytes',
 'Metamyelocytes',
 'Monocytes',
 'Myelocytes',
 'Plasma cells',
 'Proerythroblasts',
 'Mitosis',
 'Promonocytes',
 'Promyelocytes',

 'Living_Cells_Proportion',
 'Artefacts_Proportion',
 'Atypical lymphocytes_Proportion',
 'Basophils_Proportion',
 'Blasts_Proportion',
 'Eosinophils_Proportion',
 'Erythroblasts_Proportion',
 'Neutrophils_Proportion',
 'Lymphocytes_Proportion',
 'Megakaryocytes_Proportion',
 'Metamyelocytes_Proportion',
 'Monocytes_Proportion',
 'Myelocytes_Proportion',
 'Plasma cells_Proportion',
 'Proerythroblasts_Proportion',
 'Promonocytes_Proportion',
 'Promyelocytes_Proportion',
]

IMAGE_VARIABLES_TFR_HUS = [
 'Hemavision ID',
 'Hemavision DB',
   
 'Sample_Area',
 'Empty_Sample_Area',
 'RBC_Sample_Area',
 'Eukaryote_Sample_Area',
 'Stroma_Sample_Area',
 'Empty_Sample_Proportion',
 'RBC_Sample_Proportion',
 'Eukaryote_Sample_Proportion',
 'Stroma_Sample_Proportion',
 'Megakaryocyte_Sample_Count',
 'Megakaryocyte_Stroma_Count',
 'Megakaryocyte_Stroma_Count_Proportion',
 'Megakaryocyte_Sample_Density',
 'Megakaryocyte_Stroma_Density',
 'Megakaryocyte_Sample_Area',
 'Megakaryocyte_Stroma_Area',
 'Megakaryocyte_Sample_Area_Mean',
 'Megakaryocyte_Stroma_Area_Mean',
 'Lipid_Small_Sample_Area',
 'Lipid_Medium_Sample_Area',
 'Lipid_Large_Sample_Area',
 'Lipid_Total_Sample_Area',
 'Lipid_Small_Sample_Proportion',
 'Lipid_Medium_Sample_Proportion',
 'Lipid_Large_Sample_Proportion',
 'Lipid_Total_Sample_Proportion',

 'All_Cells',
 'Living_Cells',
 'Artefacts',
 'Atypical lymphocytes',
 'Basophils',
 'Blasts',
 'Eosinophils',
 'Erythroblasts',
 'Neutrophils',
 'Lymphocytes',
 'Megakaryocytes',
 'Metamyelocytes',
 'Monocytes',
 'Myelocytes',
 'Plasma cells',
 'Proerythroblasts',
 'Mitosis',
 'Promonocytes',
 'Promyelocytes',

 'Living_Cells_Proportion',
 'Artefacts_Proportion',
 'Atypical lymphocytes_Proportion',
 'Basophils_Proportion',
 'Blasts_Proportion',
 'Eosinophils_Proportion',
 'Erythroblasts_Proportion',
 'Neutrophils_Proportion',
 'Lymphocytes_Proportion',
 'Megakaryocytes_Proportion',
 'Metamyelocytes_Proportion',
 'Monocytes_Proportion',
 'Myelocytes_Proportion',
 'Plasma cells_Proportion',
 'Proerythroblasts_Proportion',
 'Promonocytes_Proportion',
 'Promyelocytes_Proportion',
]

CLINICAL_VARIABLES = ['Disease stage 1', 'Disease stage 2', 'Organ', 'Sample type', 'Patient age at diagnosis (completed years)', 'Patient gender', 'Year of diagnosis', 'Additional cytogenetic alterations at diagnosis (type and amount)', 'Possible mutations in myeloid genes (gene me and variant allele frequency)', 'BCR-ABL subtype', 'Participated in a clinical TKI discontinuation trial', 'Additional relevant comments', 'First-line tyrosine kinase inhibitor generic name before discontinuation', 'First-line tyrosine kinase inhibitor dose before discontinuation (mg)', 'First-line tyrosine kinase inhibitor duration before discontinuation (months)', 'First-line tyrosine kinase inhibitor is second-generation TKI', 'Other tyrosine kinase inhibitor before discontinuation (generic names, dose, duration, reason for TKI switch)', 'Duration of possible tyrosine kinase inhibitor pauses in total (generic name, months, reason)', 'Major tyrosine kinase inhibitor generic name before discontinuation', 'Major tyrosine kinase inhibitor is second-generation TKI', 'Last tyrosine kinase inhibitor generic name before discontinuation', 'Last tyrosine kinase inhibitor is second-generation TKI', 'Time to TKI discontinuation (months)', 'Usage of IFNa (dose, duration)', 'BCR-ABL1 transcript level at 3 months (%)', 'BCR-ABL1 transcript level at 6 months (%)', 'BCR-ABL1 transcript level at 12 months (%)', 'Time to MMR (months)', 'Time to MR4.0 (months)', 'Time to MR4.5 (months)', 'Duration of MMR before first TKI discontinuation (months)', 'Duration of MR4.0 before first TKI discontinuation (months)', 'Duration of MR4.5 before first TKI discontinuation (months)', 'BCR-ABL <0.1% IS at 12 months', 'Relapse after first TKI discontinuation', 'Timepoint of possible relapse after first TKI discontinuation (months)', 'Definition of possible relapse', 'Spleen size at diagnosis (max. distance from costal margin)', 'PB white blood cells (E9/L)', 'PB basophils at diagnosis (%)', 'PB eosinophils at diagnosis (%)', 'PB lymphocytes at diagnosis (%)', 'PB platelet count at diagnosis (E9/L)', 'PB blasts at diagnosis (%)', 'BM blasts at diagnosis (%)', 'Sokal score (original)', 'Sokal score', 'Hasford score (original)', 'Hasford score', 'EUTOS score (original)', 'EUTOS score', 'ELTS score (original)', 'ELTS score']
    
CLINICAL_VARIABLES_TFR = [
 #'Hemavision ID',
 'Center',
 #'Disease stage 1',
 #'Disease stage 2',
 #'Organ',
 #'Sample type',
 'Patient age at diagnosis (completed years)',
 'Patient gender',
 'Year of diagnosis',
 #'Additional cytogenetic alterations at diagnosis (type and amount)',
 #'Possible mutations in myeloid genes (gene me and variant allele frequency)',
 #'BCR-ABL subtype',
 #'Participated in a clinical TKI discontinuation trial',
 #'Additional relevant comments',
 'First-line tyrosine kinase inhibitor generic name before discontinuation',
 #'First-line tyrosine kinase inhibitor dose before discontinuation (mg)',
 #'First-line tyrosine kinase inhibitor duration before discontinuation (months)',
 'First-line tyrosine kinase inhibitor is second-generation TKI',
 #'Other tyrosine kinase inhibitor before discontinuation (generic names, dose, duration, reason for TKI switch)',
 #'Duration of possible tyrosine kinase inhibitor pauses in total (generic name, months, reason)',
 'Major tyrosine kinase inhibitor generic name before discontinuation',
 'Major tyrosine kinase inhibitor is second-generation TKI',
 'Time to TKI discontinuation (months)',
 #'Usage of IFNa (dose, duration)',
 'BCR-ABL1 transcript level at 3 months (%)',
 'BCR-ABL1 transcript level at 6 months (%)',
 'BCR-ABL1 transcript level at 12 months (%)',
 'Time to MMR (months)',
 'Time to MR4.0 (months)',
 'Time to MR4.5 (months)',
 'Duration of MMR before first TKI discontinuation (months)',
 'Duration of MR4.0 before first TKI discontinuation (months)',
 'Duration of MR4.5 before first TKI discontinuation (months)',
 'BCR-ABL <0.1% IS at 12 months',
 'Relapse after first TKI discontinuation',
 'Timepoint of possible relapse after first TKI discontinuation (months)',
 #'Definition of possible relapse',
 'Spleen size at diagnosis (max. distance from costal margin)',
 'PB white blood cells (E9/L)',
 'PB basophils at diagnosis (%)',
 'PB eosinophils at diagnosis (%)',
 'PB lymphocytes at diagnosis (%)',
 'PB platelet count at diagnosis (E9/L)',
 'PB blasts at diagnosis (%)',
 'BM blasts at diagnosis (%)',
 #'Sokal score (original)',
 'Sokal score',
 #'Hasford score (original)',
 'Hasford score',
 #'EUTOS score (original)',
 'EUTOS score',
 #'ELTS score (original)',
 'ELTS score',
]

CLINICAL_VARIABLES_TO_DROP_TFR = [
 'Disease stage 1',
 'Disease stage 2',
 'Organ',
 'Sample type',
 'Additional cytogenetic alterations at diagnosis (type and amount)',
 'Possible mutations in myeloid genes (gene me and variant allele frequency)',
 'BCR-ABL subtype',
 'Participated in a clinical TKI discontinuation trial',
 'Additional relevant comments',
 'First-line tyrosine kinase inhibitor dose before discontinuation (mg)',
 'Other tyrosine kinase inhibitor before discontinuation (generic names, dose, duration, reason for TKI switch)',
 'Duration of possible tyrosine kinase inhibitor pauses in total (generic name, months, reason)',
 'Usage of IFNa (dose, duration)',
 'Definition of possible relapse',
 'Sokal score (original)',
 'Hasford score (original)',
 'EUTOS score (original)',
 'ELTS score (original)',
]

tki_int_to_label_map = {
            0: "Imatinib",
            1: "Dasatinib",
            2: "Nilotinib",
            3: "Bosutinib",
}

center_int_to_label_map = {
            0: "Australia",
            1: "Japan Saga",
            2: "Norway",
            3: "Japan Ome",
            4: "Sweden Uppsala",
            5: "Sweden Örebro",
}

HEMATOSCOPE_BIOANALYST_COMPARISON_COLUMN_NAMES = {
    "Erythropoietic cells_Percentage": "Erythropoietic cells (%) - Hematoscope",
    "Blasts_Percentage": "Blasts (%) - Hematoscope",
    "Promyelocytes_Percentage": "Promyelocytes (%) - Hematoscope",
    "Myelocytes_Percentage": "Myelocytes (%) - Hematoscope",
    "Metamyelocytes_Percentage": "Metamyelocytes (%) - Hematoscope",
    "Neutrophils_Percentage": "Neutrophils (%) - Hematoscope",
    "Eosinophils_Percentage": "Eosinophils (%) - Hematoscope",
    "Basophils_Percentage": "Basophils (%) - Hematoscope",
    "Monocytes_Percentage": "Monocytes (%) - Hematoscope",
    "Plasma cells_Percentage": "Plasma cells (%) - Hematoscope",
    "Lymphocytes_Percentage": "Lymphocytes (%) - Hematoscope",
    "Mature granulopoietic cells_Percentage": "Mature granulopoietic cells (%) - Hematoscope",
    "Granulopoietic cells_Percentage": "Granulopoietic cells (%) - Hematoscope",
    "Neutrophils-Eosinophils_Percentage": "Neutrophils+Eosinophils (%) - Hematoscope",
    "ME-ratio": "M:E Ratio - Hematoscope",
    
    "Erythroid cells (%)": "Erythropoietic cells (%) - Human",
    "BM Myeloblasts (%)": "Myeloblasts (%) - Human",
    "BM Promyelocytes (%)": "Promyelocytes (%) - Human",
    "BM Myelocytes (%)": "Myelocytes (%) - Human",
    "BM Metamyelocytes (%)": "Metamyelocytes (%) - Human",
    "BM Neutrophils (%)": "Neutrophils (%) - Human",
    "BM Eosinophils (%)": "Eosinophils (%) - Human",
    "BM Basophils (%)": "Basophils (%) - Human",
    "BM Monocytes (%)": "Monocytes (%) - Human",
    "BM Plasma cells (%)": "Plasma cells (%) - Human",
    "BM Lymphocytes (%)": "Lymphocytes (%) - Human",
    "Myeloid:Erythroid Ratio": "M:E Ratio - Human",
}